name: Validate NGINX templates

on:
  push:
    paths:
      - 'templates/**'
      - '.github/**'
  pull_request:
    paths:
      - 'templates/**'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate templates with nginx container
        uses: addnab/docker-run-action@v3
        with:
          image: nginx:stable
          options: --rm -v ${{ github.workspace }}:/workspace:ro
          run: |
            set -eux
            echo "Workspace mounted:"
            ls -la /workspace || true

            # Validate each template individually by creating a minimal nginx.conf that
            # includes only that template inside the http context. This isolates parse
            # errors and avoids combining multiple server blocks in a single file.
            for f in /workspace/templates/sites/*.template; do
              [ -e "$f" ] || continue
              echo "\n--- Testing $f ---\n"
              tmpdir=/tmp/nginx-test-$(basename "$f")
              rm -rf "$tmpdir"
              mkdir -p "$tmpdir"

              # Create a minimal config that includes the template inside http {}
              cat > "$tmpdir/nginx.conf" <<EOF
              events { worker_connections 1024; }
              http {
                include /etc/nginx/mime.types;
                default_type application/octet-stream;
                include $f;
              }
              EOF

              # Show the small config and run the test
              sed -n '1,200p' "$tmpdir/nginx.conf" || true
              nginx -t -c "$tmpdir/nginx.conf"
            done
